spring:
  application:
    name: flight-consumer

  datasource:
    url: jdbc:mysql://mysql-db:3306/flights
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: flight-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    listener:
      ack-mode: record
      missing-topics-fatal: false

logging:
  level:
    org.apache.kafka: INFO
    com.example: DEBUG
